name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3


    - name: Docker Build & Push 
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: cert-nginx
        dockerfile: Dockerfile
        tags: $(date +%s), v1, latest
        registry: ghcr.io
        username: ${{ secrets.GHCR_USERNAME }}
        password: ${{ secrets.GHCR_TOKEN }}
        addLatest: true
        addTimestamp: true
        multiPlatform: true
        platform: linux/amd64,linux/arm64,linux/arm/v7
